#!/usr/bin/env bash
# Print domain and subdomain info

print_info() {
	local domain="$1"
	local subdomain="$2"
	local full_domain="${subdomain}.$domain"
	local record=$(dig +short A "@$full_domain")

	if [[ -z "$record" ]]; then
		record="N/A"
	fi
	echo "The subdomain $subdomain is a A record and points to $record"
}

if [[ -z "$1" ]]; then
  echo "Error: Please provide a domain name."
  exit 1
fi

if [[ -z "$2" ]]; then
  print_info "$1" "www"
  print_info "$1" "lb-01"
  print_info "$1" "web-01"
  print_info "$1" "web-02"
else
  print_info "$1" "$2"
fi
