#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the
# string "Ceci n'est pas une page".

echo -e "Installing Nginx.\n"
sudo apt-get update -y -qq
sudo apt-get install nginx -y

echo -e "\nNginx Setup.\n"

# Start Nginx service
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Grant user ownership of website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new file with 'Hello World!'
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure redirection from /redirect_me to a 404 picture
sudo sed -i '24i\       rewrite ^/redirect_me  https://miro.medium.com/v2/resize:fit:800/1*hFwwQAW45673VGKrMPE2qQ.png permanent;' /etc/nginx/sites-available/default

# Setup a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart

echo -e "\nSetup completed.\n"

