#!/usr/bin/env bash
# a Bash script that generates a MySQL dump and creates a compressed archive

backup_date=$(date +"%d-%m-%Y")
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czvf "$backup_date.tar.gz" backup.sql
