#!/usr/bin/env bash

# Remove Nginx config file
rm /etc/nginx/sites-enabled/default

# Config port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart

