#!/usr/bin/env bash

# Update / Install and start Nginx 
sudo apt-get update --fix-missing
sudo apt-get install nginx
service nginx start

# Remove Nginx config file
rm /etc/nginx/sites-enabled/default

# Config port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart
