#!/usr/bin/env bash
# a Bash script that configures the container to fit the requirements

service nginx stop
sed -i 's/user  nginx;/user  root;/' /etc/nginx/nginx.conf
service nginx start
pgrep -f nginx
nc -z 0 8080
